const ExecutionTask = require('../models/ExecutionTask');

/**
 * Converts AI Coach recommendations & Validation next actions into Kanban tasks
 * without creating duplicate task entries.
 */
async function createTasksFromRecommendations({ ventureId, userId, recommendations = [], nextActions = [] }) {
  if (!ventureId || !userId) return [];

  const createdOrUpdatedTasks = [];

  // 1. Process Coach Recommendations
  if (Array.isArray(recommendations)) {
    for (const rec of recommendations) {
      if (!rec.title) continue;

      const title = rec.title.trim();
      const existingTask = await ExecutionTask.findOne({ ventureId, title });

      if (!existingTask) {
        // Create new Task in 'To Do' column
        const newTask = await ExecutionTask.create({
          ventureId,
          userId,
          title,
          description: rec.explanation || rec.reason || '',
          category: 'Validation',
          status: rec.status === 'COMPLETED' ? 'Done' : 'To Do',
          priority: ['HIGH', 'MEDIUM', 'LOW'].includes(rec.priority) ? rec.priority : 'MEDIUM',
          estimatedEffort: 'Medium',
          source: 'AI_COACH',
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days out
          completedAt: rec.status === 'COMPLETED' ? new Date() : null,
        });
        createdOrUpdatedTasks.push(newTask);
      }
    }
  }

  // 2. Process Validation Next Actions
  if (Array.isArray(nextActions)) {
    for (const actionStr of nextActions) {
      if (!actionStr || typeof actionStr !== 'string') continue;
      const title = actionStr.trim();
      const existingTask = await ExecutionTask.findOne({ ventureId, title });

      if (!existingTask) {
        const newTask = await ExecutionTask.create({
          ventureId,
          userId,
          title,
          description: 'Top priority action generated by AI Validation Engine.',
          category: 'Validation',
          status: 'To Do',
          priority: 'HIGH',
          estimatedEffort: 'Medium',
          source: 'VALIDATION_ENGINE',
          dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        });
        createdOrUpdatedTasks.push(newTask);
      }
    }
  }

  return createdOrUpdatedTasks;
}

/**
 * Get all Kanban tasks for a venture grouped by status column
 */
async function getTasksForVenture(ventureId) {
  if (!ventureId) return { 'To Do': [], 'In Progress': [], 'Review': [], 'Done': [] };

  const allTasks = await ExecutionTask.find({ ventureId }).sort({ priority: -1, createdAt: -1 });

  const grouped = {
    'To Do': [],
    'In Progress': [],
    'Review': [],
    'Done': [],
  };

  allTasks.forEach((t) => {
    if (grouped[t.status]) {
      grouped[t.status].push(t);
    } else {
      grouped['To Do'].push(t);
    }
  });

  return grouped;
}

/**
 * Move a task along the Kanban workflow ('To Do' -> 'In Progress' -> 'Review' -> 'Done')
 */
async function updateTaskStatus(taskId, status) {
  if (!taskId || !status) return null;

  const validStatuses = ['To Do', 'In Progress', 'Review', 'Done'];
  if (!validStatuses.includes(status)) return null;

  const updateData = { status };
  if (status === 'Done') {
    updateData.completedAt = new Date();
  } else {
    updateData.completedAt = null;
  }

  return await ExecutionTask.findByIdAndUpdate(taskId, updateData, { new: true });
}

module.exports = {
  createTasksFromRecommendations,
  getTasksForVenture,
  updateTaskStatus,
};
